import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useAuth } from "@/hooks/use-auth";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { AlertCircle, CheckCircle2, Clock3, Database, ExternalLink, Flag, Info, Mail, RefreshCw, Settings2, ShieldCheck, TrendingDown, TrendingUp, UserRound, XCircle } from "lucide-react";

type Conversation = {
  id: number; subject?: string | null; clientContactId?: number | null;
  latestClientMessageAt?: string | null; latestMbsResponseAt?: string | null;
  disposition?: string | null; isFlagged?: boolean; elapsedMilliseconds?: number | null;
  workingMilliseconds?: number | null; category?: string | null;
  slaElapsedMilliseconds?: number | null; deadlineAt?: string | null;
  client?: { name?: string; email?: string } | null; contact?: { name?: string; email?: string } | null;
  clientManager?: { name?: string } | null;
  mailboxes?: { id: number; address: string; displayName?: string | null }[];
  outlookWebLink?: string | null;
};
type Settings = { enabled?: boolean; automaticRefreshEnabled?: boolean; autoTriageMode?: "disabled" | "shadow" | "automatic"; autoTriageConfidenceThreshold?: string | number; contactTypes?: string[]; workdayStartMinutes?: number; workdayEndMinutes?: number; fridayEndMinutes?: number; syncIntervalMinutes?: number; lastMailboxSyncAt?: string | null };
type Mailbox = { id: number; address: string; displayName?: string | null; enabled: boolean };
type Kpis = { responseTargetPercent: number; awaitingResponse: number; over24WorkingHours: number; over48WorkingHours: number; oldestOutstanding?: string | null; withinSlaLast7DaysPercent?: number | null; withinSlaLast30DaysPercent?: number | null; denominator: string };
type ShadowPeriod = { from: string; effectiveFrom: string; to: string; measurementStartAt?: string | null; measurementCoverageComplete: boolean; successes: number; failures: number; unanswered: number; denominator: number; pending: number; excluded: number; boundaryUncertain: number; percent: number | null; legacyPercent?: number | null };
type ShadowKpis = { mode: "shadow"; cohortDefinition: string; measurementStartAt?: string | null; lastBuiltAt?: string | null; periods: { sevenDays?: ShadowPeriod; previousSevenDays?: ShadowPeriod; thirtyDays?: ShadowPeriod; previousThirtyDays?: ShadowPeriod; custom?: ShadowPeriod } };
type OverdueEvent = { id: number; canonicalConversationId: number; subject?: string | null; receivedAt: string; deadlineAt: string; clientMessageCount: number; clientName?: string | null; organisationName?: string | null };
type ClassificationException = { id: number; responseEventId: number; status: string; subject?: string | null; clientName?: string | null; organisationName?: string | null; receivedAt: string; deadlineAt: string; outcome: string; handledAt?: string | null; classifiedAt: string; classifiedByFirstName?: string | null; classifiedByLastName?: string | null; classifiedByEmail?: string | null; subsequentResponseAt: string; responseWithinDeadline: boolean };
type Unmatched = { email: string; displayName?: string | null; messageCount: number; mailboxes?: string[]; lastMessageAt?: string | null };
type AuditEntry = { id?: number; disposition?: string | null; performedAt?: string | null; performedByUserId?: number | null; performedByFirstName?: string | null; performedByLastName?: string | null; performedByEmail?: string | null };
type TriageMatrix = Record<"no_response_required" | "response_required", Record<"no_response_required" | "acknowledgement_recommended" | "response_required" | "uncertain", number>>;
type TriageValidation = { totalPredictions: number; directLabeled: number; operationalOutcomeOnly: number; unresolved: number; minimumDirectLabels: number; confusionMatrix: TriageMatrix; dangerousFalseExclusions: number; dangerousFalseExclusionRate: number | null };
type TriageStatus = { mode: "disabled" | "shadow" | "automatic"; confidenceThreshold: number; validationReviewedAt?: string | null; activationApprovedAt?: string | null; lastRunAt?: string | null; lastErrorCode?: string | null; contentAccess: "not_enabled"; readiness: { ready: boolean; region: string; modelId: string; accountRetentionMode?: string | null; modelAllowedModes: string[]; retentionSafetyBasis?: string | null; availability?: { authorizationStatus?: string; regionAvailability?: string; entitlementAvailability?: string } | null; blockers: string[] }; validation: TriageValidation; predictionStatuses: Record<string, number>; automaticActivationBlocked: boolean; blockers: string[] };
const dispositions = ["no_response_required", "handled_elsewhere", "resolved_phone_meeting", "dismissed"] as const;

const prettyDisposition = (value?: string | null) => {
  if (value === "over_24") return "Over 24 hours";
  if (value === "over_48") return "Over 48 hours";
  if (value === "within_target") return "Within target";
  return value ? value.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()) : "Awaiting response";
};
const dateTime = (value?: string | null) => value ? new Date(value).toLocaleString("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "Not recorded";
const ukDateTime = (value: string) => new Date(value).toLocaleString("en-GB", { timeZone: "Europe/London", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });
const deadlineDisplay = (received?: string | null, deadline?: string | null) => {
  if (!deadline) return "Not recorded";
  const ukWeekday = (value: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/London", weekday: "short" }).format(new Date(value));
  const deadlineParts = new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/London", weekday: "short", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(new Date(deadline)).reduce<Record<string, string>>((parts, part) => (parts[part.type] = part.value, parts), {});
  if (received && ["Sat", "Sun"].includes(ukWeekday(received)) && deadlineParts.weekday === "Tue" && deadlineParts.hour === "00" && deadlineParts.minute === "00") return "End of Monday";
  return ukDateTime(deadline);
};
const minutesToTime = (value?: number) => `${String(Math.floor((value ?? 0) / 60)).padStart(2, "0")}:${String((value ?? 0) % 60).padStart(2, "0")}`;
const timeToMinutes = (value: string) => { const [hours, minutes] = value.split(":").map(Number); return hours * 60 + minutes; };
const localDateTimeInput = (date = new Date()) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
const duration = (ms?: number | null) => {
  if (!ms || ms < 0) return "Not started";
  const hours = Math.floor(ms / 3600000); const days = Math.floor(hours / 24);
  return days ? `${days}d ${hours % 24}h` : `${hours}h ${Math.floor((ms % 3600000) / 60000)}m`;
};

export default function EmailAnalytics() {
  const { user } = useAuth(); const { toast } = useToast();
  const isAdmin = user?.role === "admin" || user?.role === "manager";
  const [view, setView] = useState<"queue" | "overdue" | "exceptions" | "triage" | "history" | "quality" | "settings">("queue");
  const [category, setCategory] = useState("all"); const [search, setSearch] = useState(""); const [manager, setManager] = useState("all"); const [mailbox, setMailbox] = useState("all");
  const [disposition, setDisposition] = useState<string>("all"); const [action, setAction] = useState<{ id: number; disposition: string | null; handledAt?: string } | null>(null);
  const [mailboxDialog, setMailboxDialog] = useState(false); const [mailboxAddress, setMailboxAddress] = useState(""); const [mailboxName, setMailboxName] = useState("");
  const [settingsForm, setSettingsForm] = useState<Settings>({});
  const [auditId, setAuditId] = useState<number | null>(null);
  const [autoRefreshing, setAutoRefreshing] = useState(false);

  const queue = useQuery<Conversation[]>({ queryKey: ["/api/communication/email-analytics/queue"] });
  const history = useQuery<Conversation[]>({ queryKey: ["/api/communication/email-analytics/queue?includeResolved=true"], enabled: view === "history" });
  const kpis = useQuery<Kpis>({ queryKey: ["/api/communication/email-analytics/kpis"] });
  const shadowKpis = useQuery<ShadowKpis>({ queryKey: ["/api/communication/email-analytics/response-events/shadow-kpis"], enabled: isAdmin && view === "queue" });
  const overdue = useQuery<OverdueEvent[]>({ queryKey: ["/api/communication/email-analytics/response-events/overdue-review"], enabled: isAdmin && view === "overdue" });
  const exceptions = useQuery<ClassificationException[]>({ queryKey: ["/api/communication/email-analytics/response-events/exceptions"], enabled: isAdmin && view === "exceptions" });
  const settings = useQuery<{ settings: Settings; mailboxes: Mailbox[] }>({ queryKey: ["/api/communication/email-analytics/settings"], enabled: isAdmin });
  const sync = useQuery<{ settings: Settings; latestRun: { status?: string; completedAt?: string; startedAt?: string } | null }>({ queryKey: ["/api/communication/email-analytics/sync-status"] });
  const unmatched = useQuery<Unmatched[]>({ queryKey: ["/api/communication/email-analytics/unmatched-senders"], enabled: isAdmin && view === "quality" });
  const triageStatus = useQuery<TriageStatus>({ queryKey: ["/api/communication/email-analytics/auto-triage/status"], enabled: isAdmin && (view === "triage" || view === "settings") });
  const triageValidation = useQuery<TriageValidation>({ queryKey: ["/api/communication/email-analytics/auto-triage/validation"], enabled: isAdmin && view === "triage" });
  const effectiveSettings = settings.data?.settings || sync.data?.settings;
  const managers = useMemo(() => Array.from(new Set((queue.data || []).map((row) => row.clientManager?.name).filter(Boolean) as string[])).sort(), [queue.data]);
  const mailboxes = useMemo(() => Array.from(new Set((queue.data || []).flatMap((row) => (row.mailboxes || []).map((mailbox) => mailbox.address)))).sort(), [queue.data]);
  const rows = useMemo(() => (queue.data || []).filter((row) => {
    const haystack = `${row.subject || ""} ${row.client?.name || ""} ${row.contact?.name || ""}`.toLowerCase();
    return (!search || haystack.includes(search.toLowerCase())) && (category === "all" || row.category === category) && (disposition === "all" || (row.disposition || "awaiting") === disposition) && (manager === "all" || row.clientManager?.name === manager) && (mailbox === "all" || row.mailboxes?.some((item) => item.address === mailbox));
  }), [queue.data, search, category, disposition, manager, mailbox]);

  const invalidate = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/queue"] });
    queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/queue?includeResolved=true"] });
    queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/kpis"] });
    queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/sync-status"] });
  }, []);
  const refresh = useMutation({ mutationFn: () => apiRequest("/api/communication/email-analytics/refresh", "POST"), onSuccess: () => { invalidate(); toast({ title: "Refresh completed", description: "All available mailbox metadata has been processed." }); }, onError: (error: Error) => toast({ title: "Refresh could not be completed", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" }) });
  const dispositionMutation = useMutation({ mutationFn: async (selectedAction: { id: number; disposition: string | null; handledAt?: string }) => {
    return apiRequest(`/api/communication/email-analytics/conversations/${selectedAction.id}/${selectedAction.disposition ? "disposition" : "reopen"}`, "POST", selectedAction.disposition ? { disposition: selectedAction.disposition, handledAt: selectedAction.handledAt ? new Date(selectedAction.handledAt).toISOString() : undefined } : undefined);
  }, onMutate: async (selectedAction) => {
    setAction(null);
    await Promise.all([
      queryClient.cancelQueries({ queryKey: ["/api/communication/email-analytics/queue"] }),
      queryClient.cancelQueries({ queryKey: ["/api/communication/email-analytics/queue?includeResolved=true"] }),
    ]);
    const previousQueue = queryClient.getQueryData<Conversation[]>(["/api/communication/email-analytics/queue"]);
    const previousHistory = queryClient.getQueryData<Conversation[]>(["/api/communication/email-analytics/queue?includeResolved=true"]);
    const source = [...(previousQueue || []), ...(previousHistory || [])].find(row => row.id === selectedAction.id);
    if (selectedAction.disposition) {
      queryClient.setQueryData<Conversation[]>(["/api/communication/email-analytics/queue"], rows => (rows || []).filter(row => row.id !== selectedAction.id));
      if (source) queryClient.setQueryData<Conversation[]>(["/api/communication/email-analytics/queue?includeResolved=true"], rows => [{ ...source, disposition: selectedAction.disposition }, ...(rows || []).filter(row => row.id !== selectedAction.id)]);
    } else {
      queryClient.setQueryData<Conversation[]>(["/api/communication/email-analytics/queue?includeResolved=true"], rows => (rows || []).filter(row => row.id !== selectedAction.id));
      if (source) queryClient.setQueryData<Conversation[]>(["/api/communication/email-analytics/queue"], rows => [{ ...source, disposition: null }, ...(rows || []).filter(row => row.id !== selectedAction.id)]);
    }
    return { previousQueue, previousHistory };
  }, onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/kpis"] });
    toast({ title: "Queue updated" });
  }, onError: (error: Error, _variables, context) => {
    if (context?.previousQueue) queryClient.setQueryData(["/api/communication/email-analytics/queue"], context.previousQueue);
    if (context?.previousHistory) queryClient.setQueryData(["/api/communication/email-analytics/queue?includeResolved=true"], context.previousHistory);
    toast({ title: "Could not update conversation", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" });
  } });
  const flagMutation = useMutation({ mutationFn: ({ id, isFlagged }: { id: number; isFlagged: boolean }) => apiRequest(`/api/communication/email-analytics/conversations/${id}/flag`, "PATCH", { isFlagged }), onMutate: async ({ id, isFlagged }) => {
    await Promise.all([
      queryClient.cancelQueries({ queryKey: ["/api/communication/email-analytics/queue"] }),
      queryClient.cancelQueries({ queryKey: ["/api/communication/email-analytics/queue?includeResolved=true"] }),
    ]);
    const previousQueue = queryClient.getQueryData<Conversation[]>(["/api/communication/email-analytics/queue"]);
    const previousHistory = queryClient.getQueryData<Conversation[]>(["/api/communication/email-analytics/queue?includeResolved=true"]);
    const update = (rows?: Conversation[]) => rows?.map(row => row.id === id ? { ...row, isFlagged } : row);
    queryClient.setQueryData(["/api/communication/email-analytics/queue"], update(previousQueue));
    queryClient.setQueryData(["/api/communication/email-analytics/queue?includeResolved=true"], update(previousHistory));
    return { previousQueue, previousHistory };
  }, onSuccess: (_, variables) => toast({ title: variables.isFlagged ? "Conversation flagged" : "Flag removed" }), onError: (error: Error, _variables, context) => {
    if (context?.previousQueue) queryClient.setQueryData(["/api/communication/email-analytics/queue"], context.previousQueue);
    if (context?.previousHistory) queryClient.setQueryData(["/api/communication/email-analytics/queue?includeResolved=true"], context.previousHistory);
    toast({ title: "Could not update flag", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" });
  } });
  const saveSettings = useMutation({ mutationFn: () => apiRequest("/api/communication/email-analytics/settings", "PUT", settingsForm), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/settings"] }); queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/sync-status"] }); toast({ title: "Settings saved" }); }, onError: () => toast({ title: "Settings could not be saved", variant: "destructive" }) });
  const addMailbox = useMutation({ mutationFn: () => apiRequest("/api/communication/email-analytics/mailboxes", "POST", { address: mailboxAddress, displayName: mailboxName }), onSuccess: () => { setMailboxDialog(false); setMailboxAddress(""); setMailboxName(""); queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/settings"] }); toast({ title: "Mailbox added" }); }, onError: () => toast({ title: "Mailbox could not be added", variant: "destructive" }) });
  const toggleMailbox = useMutation({ mutationFn: ({ id, enabled }: { id: number; enabled: boolean }) => apiRequest(`/api/communication/email-analytics/mailboxes/${id}`, "PATCH", { enabled }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/settings"] }) });
  const rebuildShadow = useMutation({ mutationFn: () => apiRequest("/api/communication/email-analytics/response-events/rebuild", "POST"), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/response-events/shadow-kpis"] }); toast({ title: "Shadow response events rebuilt" }); }, onError: (error: Error) => toast({ title: "Shadow rebuild failed", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" }) });
  const classifyOverdue = useMutation({ mutationFn: ({ id, outcome, handledAt }: { id: number; outcome: string; handledAt?: string }) => apiRequest(`/api/communication/email-analytics/response-events/${id}/classify`, "POST", { outcome, handledAt: handledAt ? new Date(handledAt).toISOString() : undefined }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/response-events/overdue-review"] }); queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/response-events/shadow-kpis"] }); toast({ title: "Overdue event classified" }); }, onError: (error: Error) => toast({ title: "Classification failed", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" }) });
  const resolveException = useMutation({ mutationFn: ({ id, outcome }: { id: number; outcome?: string }) => apiRequest(`/api/communication/email-analytics/response-events/exceptions/${id}/resolve`, "POST", { outcome }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/response-events/exceptions"] }); queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/response-events/shadow-kpis"] }); toast({ title: "Classification exception resolved" }); }, onError: (error: Error) => toast({ title: "Exception could not be resolved", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" }) });
  const reviewTriageValidation = useMutation({ mutationFn: () => apiRequest("/api/communication/email-analytics/auto-triage/validation/review", "POST", { acknowledged: true }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/communication/email-analytics/auto-triage/status"] }); toast({ title: "Validation review recorded" }); }, onError: (error: Error) => toast({ title: "Validation is not ready for approval", description: error.message.replace(/^\d+:\s*/, ""), variant: "destructive" }) });

  const automaticRefreshEnabled = effectiveSettings?.automaticRefreshEnabled;
  const automaticRefreshInterval = Math.max(30, effectiveSettings?.syncIntervalMinutes || 30);
  useEffect(() => {
    if (!automaticRefreshEnabled) return;
    let cancelled = false;
    let running = false;
    const refreshIfDue = async () => {
      if (running || cancelled) return;
      running = true;
      setAutoRefreshing(true);
      try {
        const response = await apiRequest("/api/communication/email-analytics/refresh-if-due", "POST");
        const result = await response.json();
        if (!cancelled && result.status === "refreshed") invalidate();
      } catch (error) {
        console.error("[email-analytics] Automatic refresh request failed", error);
      } finally {
        running = false;
        if (!cancelled) setAutoRefreshing(false);
      }
    };
    void refreshIfDue();
    const timer = window.setInterval(() => void refreshIfDue(), automaticRefreshInterval * 60_000);
    return () => {
      cancelled = true;
      window.clearInterval(timer);
    };
  }, [automaticRefreshEnabled, automaticRefreshInterval, invalidate]);

  if (queue.isError || kpis.isError) return <ErrorState retry={() => { queue.refetch(); kpis.refetch(); }} />;
  const data = kpis.data;
  const currentSettings = effectiveSettings;
  const lastUpdated = sync.data?.settings?.lastMailboxSyncAt;
  return (
    <div className="space-y-5 max-w-[1500px]">
      <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-start lg:justify-between">
        <div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500"><Mail className="h-4 w-4 text-teal-700" /> Communication</div><h1 className="mt-2 text-2xl font-semibold tracking-tight text-slate-900">Email analytics</h1><p className="mt-1 max-w-2xl text-sm text-slate-600">A shared control surface for making sure genuine client messages are acknowledged and accounted for.</p></div>
        <div className="flex flex-wrap items-center gap-2"><span className="text-xs text-slate-500">{autoRefreshing ? "Refreshing automatically..." : lastUpdated ? `Last updated ${dateTime(lastUpdated)}` : "No completed sync recorded"}</span>{isAdmin && <Button variant="outline" size="sm" onClick={() => refresh.mutate()} disabled={refresh.isPending || autoRefreshing}><RefreshCw className={`mr-2 h-4 w-4 ${refresh.isPending || autoRefreshing ? "animate-spin" : ""}`} />{refresh.isPending ? "Refreshing mailboxes..." : "Refresh now"}</Button>}</div>
      </header>
      <div className="flex flex-wrap gap-1 border-b border-slate-200"><Tab active={view === "queue"} onClick={() => setView("queue")}>Live queue</Tab>{isAdmin && <><Tab active={view === "overdue"} onClick={() => setView("overdue")}>Overdue review</Tab><Tab active={view === "exceptions"} onClick={() => setView("exceptions")}>Classification exceptions</Tab><Tab active={view === "triage"} onClick={() => setView("triage")}>Triage validation</Tab></>}<Tab active={view === "history"} onClick={() => setView("history")}>Handled history</Tab>{isAdmin && <><Tab active={view === "quality"} onClick={() => setView("quality")}>Data quality</Tab><Tab active={view === "settings"} onClick={() => { setView("settings"); setSettingsForm(currentSettings || {}); }}>Configuration</Tab></>}</div>
      {view === "queue" ? <><KpiStrip data={data} />{isAdmin && <ShadowKpiPanel data={shadowKpis.data} loading={shadowKpis.isLoading} rebuilding={rebuildShadow.isPending} onRebuild={() => rebuildShadow.mutate()} />}<section className="rounded-lg border border-slate-200 bg-white shadow-sm"><QueueToolbar search={search} setSearch={setSearch} category={category} setCategory={setCategory} disposition={disposition} setDisposition={setDisposition} manager={manager} setManager={setManager} mailbox={mailbox} setMailbox={setMailbox} managers={managers} mailboxes={mailboxes} /><QueueTable rows={rows} loading={queue.isLoading} canManage={isAdmin} onAction={(id, value) => setAction({ id, disposition: value, handledAt: localDateTimeInput() })} onFlag={(id, isFlagged) => flagMutation.mutate({ id, isFlagged })} onInspect={setAuditId} /></section><PrivacyNote /></> : view === "overdue" ? <OverdueReview rows={overdue.data || []} loading={overdue.isLoading} saving={classifyOverdue.isPending} onClassify={(id, outcome, handledAt) => classifyOverdue.mutate({ id, outcome, handledAt })} /> : view === "exceptions" ? <ClassificationExceptions rows={exceptions.data || []} loading={exceptions.isLoading} saving={resolveException.isPending} onResolve={(id, outcome) => resolveException.mutate({ id, outcome })} /> : view === "triage" ? <TriageValidationView status={triageStatus.data} validation={triageValidation.data} loading={triageStatus.isLoading || triageValidation.isLoading} reviewing={reviewTriageValidation.isPending} onReview={() => reviewTriageValidation.mutate()} /> : view === "history" ? <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><h2 className="font-semibold text-slate-900">Handled conversation history</h2><p className="mt-0.5 text-xs text-slate-500">Legitimate outcomes remain visible and can be reopened by a manager.</p></div><QueueTable rows={history.data || []} loading={history.isLoading} canManage={isAdmin} onAction={(id) => setAction({ id, disposition: null })} onFlag={(id, isFlagged) => flagMutation.mutate({ id, isFlagged })} onInspect={setAuditId} /></section> : view === "quality" ? <QualityView rows={unmatched.data || []} loading={unmatched.isLoading} /> : <SettingsView data={settings.data} form={settingsForm} setForm={setSettingsForm} onSave={() => saveSettings.mutate()} saving={saveSettings.isPending} onAdd={() => setMailboxDialog(true)} onToggle={(id, enabled) => toggleMailbox.mutate({ id, enabled })} /> }
      <AlertDialog open={!!action} onOpenChange={(open) => !open && setAction(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{action?.disposition ? "Record this handling outcome?" : "Reopen this conversation?"}</AlertDialogTitle><AlertDialogDescription>{action?.disposition ? "This keeps the queue accountable without treating a legitimate non-email resolution as a missed response." : "The conversation will return to the live queue for follow-up."}</AlertDialogDescription></AlertDialogHeader>{action?.disposition && ["handled_elsewhere", "resolved_phone_meeting"].includes(action.disposition) && <div><Label htmlFor="actual-handled-at">When was it actually handled?</Label><Input id="actual-handled-at" type="datetime-local" className="mt-1" value={action.handledAt || ""} onChange={(event) => setAction(current => current ? { ...current, handledAt: event.target.value } : current)} /><p className="mt-1 text-xs text-slate-500">Change this when recording an outcome retrospectively.</p></div>}<AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => action && dispositionMutation.mutate({ ...action })} disabled={!action || dispositionMutation.isPending}>{dispositionMutation.isPending ? "Saving..." : "Confirm"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
      <Dialog open={mailboxDialog} onOpenChange={setMailboxDialog}><DialogContent><DialogHeader><DialogTitle>Add monitored mailbox</DialogTitle></DialogHeader><div className="space-y-4"><div><Label htmlFor="mailbox-address">Email address</Label><Input id="mailbox-address" type="email" value={mailboxAddress} onChange={(e) => setMailboxAddress(e.target.value)} placeholder="practice@firm.co.uk" /></div><div><Label htmlFor="mailbox-name">Display name <span className="font-normal text-slate-400">(optional)</span></Label><Input id="mailbox-name" value={mailboxName} onChange={(e) => setMailboxName(e.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setMailboxDialog(false)}>Cancel</Button><Button onClick={() => addMailbox.mutate()} disabled={!mailboxAddress || addMailbox.isPending}>Add mailbox</Button></DialogFooter></DialogContent></Dialog>
      <AuditDialog id={auditId} onClose={() => setAuditId(null)} />
    </div>
  );
}

function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button onClick={onClick} className={`border-b-2 px-3 py-2 text-sm font-medium transition-colors ${active ? "border-teal-700 text-teal-800" : "border-transparent text-slate-500 hover:text-slate-800"}`}>{children}</button>; }
function KpiStrip({ data }: { data?: Kpis }) {
  const items = [
    { label: "Service standard", value: data ? `${data.responseTargetPercent}% of genuine client emails responded to within 24 hours, excluding weekends` : "—", icon: ShieldCheck, tone: "text-blue-700 bg-blue-50", compact: true, wide: true },
    { label: "Awaiting response", value: data?.awaitingResponse ?? "—", icon: Clock3, tone: "text-amber-700 bg-amber-50" },
    { label: "Over 24 hours", value: data?.over24WorkingHours ?? "—", icon: AlertCircle, tone: "text-orange-700 bg-orange-50" },
    { label: "Over 48 hours", value: data?.over48WorkingHours ?? "—", icon: XCircle, tone: "text-rose-700 bg-rose-50" },
    { label: "Oldest outstanding", value: data?.oldestOutstanding ? dateTime(data.oldestOutstanding) : "—", icon: Clock3, tone: "text-slate-700 bg-slate-100", compact: true },
    { label: "Responded within target · 7 days", value: data?.withinSlaLast7DaysPercent == null ? "—" : `${data.withinSlaLast7DaysPercent}%`, icon: CheckCircle2, tone: "text-teal-700 bg-teal-50" },
    { label: "Responded within target · 30 days", value: data?.withinSlaLast30DaysPercent == null ? "—" : `${data.withinSlaLast30DaysPercent}%`, icon: CheckCircle2, tone: "text-teal-700 bg-teal-50" },
  ];
  return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-8">{items.map((item) => <Card key={item.label} className={`border-slate-200 shadow-sm ${item.wide ? "col-span-2" : ""}`}><CardContent className="flex items-center gap-3 p-4"><div className={`rounded-md p-2 ${item.tone}`}><item.icon className="h-4 w-4" /></div><div><p className="text-xs text-slate-500">{item.label}</p><p className={`mt-0.5 font-semibold text-slate-900 ${item.compact ? "text-sm" : "text-xl"}`}>{item.value}</p></div></CardContent></Card>)}</div>;
}
function ShadowKpiPanel({ data, loading, rebuilding, onRebuild }: { data?: ShadowKpis; loading: boolean; rebuilding: boolean; onRebuild: () => void }) {
  const periods = [{ label: "Last 7 days", value: data?.periods.sevenDays, previous: data?.periods.previousSevenDays }, { label: "Last 30 days", value: data?.periods.thirtyDays, previous: data?.periods.previousThirtyDays }];
  return <section className="rounded-lg border border-dashed border-indigo-300 bg-indigo-50/40 p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Badge className="border-0 bg-indigo-100 text-indigo-800">Shadow only</Badge><h2 className="font-semibold text-slate-900">Response-event KPI preview</h2></div><p className="mt-1 text-xs text-slate-600">The production KPI cards above are unchanged. This preview excludes pending events until they are handled or their deadline matures.</p></div><Button variant="outline" size="sm" onClick={onRebuild} disabled={rebuilding}><RefreshCw className={`mr-2 h-4 w-4 ${rebuilding ? "animate-spin" : ""}`} />{rebuilding ? "Rebuilding..." : "Rebuild shadow events"}</Button></div>
    {loading ? <div className="mt-4 h-20 animate-pulse rounded bg-indigo-100/70" /> : <><div className="mt-4 grid gap-3 md:grid-cols-2">{periods.map(({ label, value, previous }) => { const movement = value?.percent != null && previous?.percent != null ? Math.round((value.percent - previous.percent) * 10) / 10 : null; const legacyDifference = value?.percent != null && value?.legacyPercent != null ? Math.round((value.percent - value.legacyPercent) * 10) / 10 : null; return <div key={label} className="rounded-md border border-indigo-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-indigo-700">{label}</p><div className="mt-2 flex items-baseline gap-2"><span className="text-2xl font-semibold text-slate-900">{value?.percent == null ? "—" : `${value.percent}%`}</span><span className={`inline-flex items-center text-xs font-medium ${movement == null ? "text-slate-500" : movement >= 0 ? "text-teal-700" : "text-rose-700"}`}>{movement == null ? "No comparison yet" : <>{movement >= 0 ? <TrendingUp className="mr-1 h-3 w-3" /> : <TrendingDown className="mr-1 h-3 w-3" />}{movement > 0 ? "+" : ""}{movement} pp vs previous {label.includes("7") ? "7" : "30"} days</>}</span></div><p className="mt-1 text-xs text-slate-500">{value?.successes ?? 0} successful / {value?.denominator ?? 0} reportable</p><p className="mt-1 text-xs text-slate-500">Previous: {previous?.percent == null ? "—" : `${previous.percent}%`} · {previous?.denominator ?? 0} reportable · {previous?.pending ?? 0} pending</p><p className="mt-1 text-xs text-slate-500">Legacy conversation KPI: {value?.legacyPercent == null ? "—" : `${value.legacyPercent}%`}{legacyDifference == null ? "" : ` · ${legacyDifference > 0 ? "+" : ""}${legacyDifference} pp event-based difference`}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-600"><span>Pending: <strong>{value?.pending ?? 0}</strong></span><span>Failures: <strong>{value?.failures ?? 0}</strong></span><span>Excluded: <strong>{value?.excluded ?? 0}</strong></span><span>Boundary uncertain: <strong>{value?.boundaryUncertain ?? 0}</strong></span></div>{value && !value.measurementCoverageComplete && <p className="mt-2 text-xs font-medium text-amber-700">Partial measurement coverage: the cohort begins at the measurement start date.</p>}</div>; })}</div><p className="mt-3 text-xs text-slate-500">Measurement starts {data?.measurementStartAt ? dateTime(data.measurementStartAt) : "when shadow tracking is configured"}. Boundary-uncertain events are excluded. Last built {data?.lastBuiltAt ? dateTime(data.lastBuiltAt) : "not yet"}. The legacy KPI uses each conversation's latest client message; the event KPI measures every response obligation, so repeat obligations can change the result.</p></>}
  </section>;
}
function OverdueReview({ rows, loading, saving, onClassify }: { rows: OverdueEvent[]; loading: boolean; saving: boolean; onClassify: (id: number, outcome: string, handledAt?: string) => void }) {
  const [times, setTimes] = useState<Record<number, string>>({});
  if (loading) return <div className="h-32 animate-pulse rounded-lg bg-slate-100" />;
  return <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><h2 className="font-semibold text-slate-900">Monday overdue review</h2><p className="mt-1 text-xs text-slate-500">Only matured events with no email response or final manual classification appear here. In-deadline emails remain in the live queue.</p></div>{!rows.length ? <div className="p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-teal-600" /><p className="mt-3 font-medium text-slate-800">No overdue events need review</p></div> : <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Client / subject", "Client email", "Deadline", "Handling time", "Classification"].map(label => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.id}><td className="max-w-[360px] px-4 py-3"><p className="font-medium text-slate-900">{row.organisationName || row.clientName || "Client"}</p><p className="truncate text-xs text-slate-500">{row.subject || "No subject"}{row.clientMessageCount > 1 ? ` · ${row.clientMessageCount} messages` : ""}</p></td><td className="whitespace-nowrap px-4 py-3">{dateTime(row.receivedAt)}</td><td className="whitespace-nowrap px-4 py-3 text-rose-700">{dateTime(row.deadlineAt)}</td><td className="px-4 py-3"><Input type="datetime-local" className="h-8 w-44 text-xs" value={times[row.id] || localDateTimeInput()} onChange={event => setTimes(current => ({ ...current, [row.id]: event.target.value }))} /></td><td className="px-4 py-3"><Select value="" disabled={saving} onValueChange={outcome => onClassify(row.id, outcome, times[row.id] || localDateTimeInput())}><SelectTrigger className="h-8 w-52 text-xs"><SelectValue placeholder="Record review outcome" /></SelectTrigger><SelectContent><SelectItem value="excluded_no_response_required">No response required</SelectItem><SelectItem value="pass_handled_elsewhere">Handled elsewhere</SelectItem><SelectItem value="pass_resolved_phone_meeting">Resolved by phone/meeting</SelectItem><SelectItem value="fail_dismissed">Dismissed</SelectItem><SelectItem value="fail_unanswered">Leave as genuinely unanswered</SelectItem></SelectContent></Select></td></tr>)}</tbody></table></div>}</section>;
}
function ClassificationExceptions({ rows, loading, saving, onResolve }: { rows: ClassificationException[]; loading: boolean; saving: boolean; onResolve: (id: number, outcome?: string) => void }) {
  if (loading) return <div className="h-32 animate-pulse rounded-lg bg-slate-100" />;
  return <section className="rounded-lg border border-amber-200 bg-white shadow-sm"><div className="border-b border-amber-200 bg-amber-50/60 p-4"><h2 className="font-semibold text-slate-900">Classification exceptions</h2><p className="mt-1 text-xs text-slate-600">A later MBS email was detected after a manual classification. The original classification remains unchanged until management confirms or corrects it.</p></div>{!rows.length ? <div className="p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-teal-600" /><p className="mt-3 font-medium text-slate-800">No classification exceptions need review</p></div> : <div className="space-y-3 p-4">{rows.map(row => { const actor = [row.classifiedByFirstName, row.classifiedByLastName].filter(Boolean).join(" ") || row.classifiedByEmail || "Practice user"; return <div key={row.id} className="rounded-lg border border-amber-200 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-medium text-slate-900">{row.organisationName || row.clientName || "Client"} · {row.subject || "No subject"}</p><div className="mt-2 grid gap-x-6 gap-y-1 text-xs text-slate-600 sm:grid-cols-2"><span>Client email: <strong>{dateTime(row.receivedAt)}</strong></span><span>Deadline: <strong>{dateTime(row.deadlineAt)}</strong></span><span>Manual classification: <strong>{prettyDisposition(row.outcome)}</strong></span><span>Classified by: <strong>{actor}, {dateTime(row.classifiedAt)}</strong></span><span>Handling time: <strong>{dateTime(row.handledAt)}</strong></span><span>Later MBS response: <strong>{dateTime(row.subsequentResponseAt)}</strong></span></div><Badge className={`mt-3 border-0 ${row.responseWithinDeadline ? "bg-teal-50 text-teal-700" : "bg-rose-50 text-rose-700"}`}>{row.responseWithinDeadline ? "Response was inside original deadline" : "Response was outside original deadline"}</Badge></div><div className="flex shrink-0 flex-col gap-2"><Button size="sm" variant="outline" disabled={saving} onClick={() => onResolve(row.id)}>Confirm original classification</Button><Select value="" disabled={saving} onValueChange={outcome => onResolve(row.id, outcome)}><SelectTrigger className="h-9 w-56 text-xs"><SelectValue placeholder="Correct classification" /></SelectTrigger><SelectContent><SelectItem value={row.responseWithinDeadline ? "pass_email_response" : "fail_late_response"}>Use detected email response</SelectItem><SelectItem value="excluded_no_response_required">No response required</SelectItem><SelectItem value="pass_handled_elsewhere">Handled elsewhere</SelectItem><SelectItem value="pass_resolved_phone_meeting">Resolved by phone/meeting</SelectItem><SelectItem value="fail_dismissed">Dismissed</SelectItem><SelectItem value="fail_unanswered">Genuinely unanswered</SelectItem></SelectContent></Select></div></div></div>; })}</div>}</section>;
}
function TriageValidationView({ status, validation, loading, reviewing, onReview }: { status?: TriageStatus; validation?: TriageValidation; loading: boolean; reviewing: boolean; onReview: () => void }) {
  const report = validation || status?.validation;
  const labels: (keyof TriageMatrix["no_response_required"])[] = ["no_response_required", "acknowledgement_recommended", "response_required", "uncertain"];
  if (loading) return <div className="h-64 animate-pulse rounded-lg bg-slate-100" />;
  return <div className="space-y-5">
    <section className="rounded-lg border border-indigo-200 bg-indigo-50/50 p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Badge className="border-0 bg-indigo-100 text-indigo-800">{prettyDisposition(status?.mode || "disabled")}</Badge><h2 className="font-semibold text-slate-900">Automatic triage safeguards</h2></div><p className="mt-1 max-w-3xl text-sm text-slate-600">This feature only keeps content-free labels, confidence values, fixed reason codes, model details, and timestamps. Email text, previews, attachments, prompts, and free-text explanations are not retained.</p></div><Badge className={`border-0 ${status?.readiness.ready ? "bg-teal-100 text-teal-800" : "bg-amber-100 text-amber-800"}`}>{status?.readiness.ready ? "Bedrock gate passed" : "Inference blocked"}</Badge></div>
      <div className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><div className="rounded border border-indigo-100 bg-white p-3"><p className="text-xs uppercase tracking-wide text-slate-500">Bedrock region</p><p className="mt-1 font-medium text-slate-800">{status?.readiness.region || "Checking"}</p></div><div className="rounded border border-indigo-100 bg-white p-3"><p className="text-xs uppercase tracking-wide text-slate-500">Account retention</p><p className="mt-1 font-medium text-slate-800">{status?.readiness.accountRetentionMode || "Not verified"}</p></div><div className="rounded border border-indigo-100 bg-white p-3"><p className="text-xs uppercase tracking-wide text-slate-500">Runtime protection</p><p className="mt-1 font-medium text-slate-800">{status?.readiness.retentionSafetyBasis ? "Incompatible requests blocked" : "Not verified"}</p></div><div className="rounded border border-indigo-100 bg-white p-3"><p className="text-xs uppercase tracking-wide text-slate-500">Microsoft content access</p><p className="mt-1 font-medium text-slate-800">Not enabled</p></div></div>
      <div className="mt-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><p className="font-medium">Why automatic triage is unavailable</p><ul className="mt-1 list-disc space-y-1 pl-5 text-xs">{(status?.blockers || ["Status could not be loaded."]).map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></div>
    </section>
    <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="font-semibold text-slate-900">Shadow validation report</h2><p className="mt-1 text-sm text-slate-500">Only a later manual classification gives direct ground truth. Handled elsewhere and phone/meeting outcomes are displayed separately because they do not say whether the email itself required a reply.</p></div><Button variant="outline" size="sm" onClick={onReview} disabled={reviewing || (report?.directLabeled || 0) < (report?.minimumDirectLabels || 25) || !!report?.dangerousFalseExclusions}>{reviewing ? "Recording..." : "Record validation review"}</Button></div>
      <div className="grid gap-3 p-5 sm:grid-cols-4"><MetricCard label="Predictions" value={report?.totalPredictions ?? 0} /><MetricCard label="Directly labelled" value={`${report?.directLabeled ?? 0} / ${report?.minimumDirectLabels ?? 25}`} /><MetricCard label="Operational outcome only" value={report?.operationalOutcomeOnly ?? 0} /><MetricCard label="Dangerous false exclusions" value={report?.dangerousFalseExclusions ?? 0} alert={!!report?.dangerousFalseExclusions} /></div>
      <div className="overflow-x-auto border-t border-slate-100 p-5"><p className="mb-3 text-sm font-medium text-slate-800">Confusion matrix — actual manual classification by shadow prediction</p><table className="min-w-[720px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">Actual outcome</th>{labels.map(label => <th key={label} className="px-3 py-2">{prettyDisposition(label)}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{(["no_response_required", "response_required"] as const).map(actual => <tr key={actual}><td className="px-3 py-3 font-medium text-slate-800">{prettyDisposition(actual)}</td>{labels.map(predicted => <td key={predicted} className={`px-3 py-3 ${actual === "response_required" && predicted === "no_response_required" && (report?.confusionMatrix?.[actual]?.[predicted] || 0) > 0 ? "font-semibold text-rose-700" : "text-slate-700"}`}>{report?.confusionMatrix?.[actual]?.[predicted] || 0}</td>)}</tr>)}</tbody></table>
        <p className="mt-3 text-xs text-slate-500">A dangerous false exclusion is a message manually judged to need a response but predicted as no response required. Automatic exclusions remain unavailable until there are enough directly labelled examples, that count is zero, the review is recorded, the Bedrock gate passes, and Microsoft content access is separately approved.</p>
      </div>
    </section>
  </div>;
}
function MetricCard({ label, value, alert }: { label: string; value: string | number; alert?: boolean }) { return <div className={`rounded-md border p-3 ${alert ? "border-rose-200 bg-rose-50" : "border-slate-200 bg-slate-50"}`}><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-xl font-semibold ${alert ? "text-rose-700" : "text-slate-900"}`}>{value}</p></div>; }
function QueueToolbar({ search, setSearch, category, setCategory, disposition, setDisposition, manager, setManager, mailbox, setMailbox, managers, mailboxes }: { search: string; setSearch: (value: string) => void; category: string; setCategory: (value: string) => void; disposition: string; setDisposition: (value: string) => void; manager: string; setManager: (value: string) => void; mailbox: string; setMailbox: (value: string) => void; managers: string[]; mailboxes: string[] }) {
  return <div className="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold text-slate-900">Outstanding client conversations</h2><p className="mt-0.5 text-xs text-slate-500">Longest waiting first, without ranking individual staff.</p></div><div className="flex flex-wrap gap-2"><Input className="h-9 w-48" placeholder="Search subject or client" value={search} onChange={(e) => setSearch(e.target.value)} /><Select value={manager} onValueChange={setManager}><SelectTrigger className="h-9 w-36"><SelectValue placeholder="Manager" /></SelectTrigger><SelectContent><SelectItem value="all">All managers</SelectItem>{managers.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={mailbox} onValueChange={setMailbox}><SelectTrigger className="h-9 w-36"><SelectValue placeholder="Mailbox" /></SelectTrigger><SelectContent><SelectItem value="all">All mailboxes</SelectItem>{mailboxes.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={category} onValueChange={setCategory}><SelectTrigger className="h-9 w-36"><SelectValue placeholder="Category" /></SelectTrigger><SelectContent><SelectItem value="all">All urgency</SelectItem><SelectItem value="within_target">Within target</SelectItem><SelectItem value="over_24">Over 24 hours</SelectItem><SelectItem value="over_48">Over 48 hours</SelectItem></SelectContent></Select><Select value={disposition} onValueChange={setDisposition}><SelectTrigger className="h-9 w-36"><SelectValue placeholder="Disposition" /></SelectTrigger><SelectContent><SelectItem value="all">All dispositions</SelectItem><SelectItem value="awaiting">Awaiting response</SelectItem>{dispositions.map((item) => <SelectItem key={item} value={item}>{prettyDisposition(item)}</SelectItem>)}</SelectContent></Select></div></div>;
}
function QueueTable({ rows, loading, canManage, onAction, onFlag, onInspect }: { rows: Conversation[]; loading: boolean; canManage: boolean; onAction: (id: number, disposition: string | null) => void; onFlag: (id: number, isFlagged: boolean) => void; onInspect: (id: number) => void }) {
  if (loading) return <div className="space-y-3 p-5">{[1, 2, 3, 4].map((i) => <div key={i} className="h-14 animate-pulse rounded bg-slate-100" />)}</div>;
  if (!rows.length) return <div className="p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-teal-600" /><p className="mt-3 font-medium text-slate-800">Nothing needs attention</p><p className="mt-1 text-sm text-slate-500">Try widening the filters, or check again after the next sync.</p></div>;
  return <div className="overflow-x-auto"><table className="min-w-[1180px] w-full text-left">
    <thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr>{["Conversation", "Mailbox", "Latest client message", "Response time", "Category", "Disposition", "Action"].map((h) => <th key={h} className="whitespace-nowrap px-4 py-3 font-semibold">{h}</th>)}</tr></thead>
    <tbody className="divide-y divide-slate-100">{rows.map((row) => {
      const person = row.contact?.name || row.client?.name || (row.clientContactId ? `Contact ${row.clientContactId}` : "Unmatched contact");
      const categoryClass = row.category === "over_48" ? "bg-rose-50 text-rose-700" : row.category === "over_24" ? "bg-orange-50 text-orange-700" : "bg-teal-50 text-teal-700";
      const mailboxLabel = row.mailboxes?.map(m => m.displayName || m.address).join(", ") || "Not recorded";
       return <tr key={row.id} className={row.isFlagged ? "bg-amber-50/60 hover:bg-amber-50" : "hover:bg-slate-50/80"}>
        <td className="max-w-[360px] px-4 py-3">
          <button className="block max-w-full text-left" onClick={() => onInspect(row.id)}>
             <p className="flex items-center gap-2 truncate text-sm font-medium text-slate-900 hover:text-teal-800">{row.isFlagged && <Flag className="h-3.5 w-3.5 shrink-0 fill-amber-500 text-amber-600" aria-label="Flagged issue" />}<span className="truncate">{row.subject || "No subject"}</span>{row.isFlagged && <span className="shrink-0 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-amber-800">Issue</span>}</p>
            <p className="mt-0.5 flex items-center gap-1 text-xs text-slate-500"><UserRound className="h-3 w-3" />{person}{row.client?.name && row.client.name !== person ? ` · ${row.client.name}` : ""}{row.clientManager?.name ? ` · ${row.clientManager.name}` : ""}</p>
          </button>
        </td>
        <td className="max-w-[220px] px-4 py-3 text-xs text-slate-600">{mailboxLabel}</td>
        <td className="whitespace-nowrap px-4 py-3 text-sm text-slate-600">{dateTime(row.latestClientMessageAt)}</td>
        <td className="whitespace-nowrap px-4 py-3 text-sm font-medium text-slate-800"><span>{duration(row.slaElapsedMilliseconds ?? row.workingMilliseconds ?? row.elapsedMilliseconds)}</span>{row.deadlineAt && <span className="mt-0.5 block text-[11px] font-normal text-slate-500">Due {deadlineDisplay(row.latestClientMessageAt, row.deadlineAt)}</span>}</td>
        <td className="px-4 py-3"><Badge className={`border-0 font-medium ${categoryClass}`}>{prettyDisposition(row.category)}</Badge></td>
        <td className="whitespace-nowrap px-4 py-3 text-sm text-slate-600">{prettyDisposition(row.disposition)}</td>
        <td className="px-4 py-3"><div className="flex items-center gap-2">
           {canManage && <Button type="button" variant="outline" size="sm" className={row.isFlagged ? "h-8 border-amber-300 bg-amber-100 px-2 text-amber-800 hover:bg-amber-200" : "h-8 px-2 text-slate-600"} onClick={() => onFlag(row.id, !row.isFlagged)} title={row.isFlagged ? "Remove issue flag" : "Mark as a true issue"} aria-label={row.isFlagged ? "Remove issue flag" : "Mark as a true issue"} aria-pressed={!!row.isFlagged}><Flag className={`h-3.5 w-3.5 ${row.isFlagged ? "fill-current" : ""}`} /></Button>}
          {row.outlookWebLink && <a href={row.outlookWebLink} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center gap-1 rounded-md border border-slate-200 px-2 text-xs font-medium text-slate-700 hover:bg-slate-50"><ExternalLink className="h-3 w-3" />Outlook</a>}
          {canManage ? <Select value="" onValueChange={(value) => onAction(row.id, value === "reopen" ? null : value)}><SelectTrigger className="h-8 w-36 text-xs"><SelectValue placeholder={row.disposition ? "Change outcome" : "Record outcome"} /></SelectTrigger><SelectContent>{row.disposition && <SelectItem value="reopen">Reopen</SelectItem>}{dispositions.map((item) => <SelectItem key={item} value={item}>{prettyDisposition(item)}</SelectItem>)}</SelectContent></Select> : <span className="text-xs text-slate-400">Manager action</span>}
        </div></td>
      </tr>;
    })}</tbody>
  </table></div>;
}
function AuditDialog({ id, onClose }: { id: number | null; onClose: () => void }) { const audit = useQuery<AuditEntry[]>({ queryKey: [`/api/communication/email-analytics/conversations/${id}/audit`], enabled: id !== null }); return <Dialog open={id !== null} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>Conversation audit</DialogTitle></DialogHeader>{audit.isLoading ? <div className="space-y-2">{[1, 2].map((i) => <div key={i} className="h-10 animate-pulse rounded bg-slate-100" />)}</div> : audit.isError ? <p className="text-sm text-rose-700">Audit history could not be loaded.</p> : !audit.data?.length ? <p className="text-sm text-slate-500">No disposition changes recorded.</p> : <div className="space-y-2">{audit.data.map((entry, index) => { const actor = [entry.performedByFirstName, entry.performedByLastName].filter(Boolean).join(" ") || entry.performedByEmail || "Practice user"; return <div key={entry.id || index} className="flex items-center justify-between rounded border border-slate-200 px-3 py-2 text-sm"><div><span className="font-medium text-slate-800">{prettyDisposition(entry.disposition)}</span><span className="ml-2 text-xs text-slate-500">by {actor}</span></div><span className="text-xs text-slate-500">{dateTime(entry.performedAt)}</span></div>; })}</div>}</DialogContent></Dialog>; }
function PrivacyNote() { return <div className="flex gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-teal-700" /><div><p className="font-medium text-slate-800">A service safeguard, not a staff score</p><p className="mt-1">The queue measures whether genuine client conversations receive a timely response. Dispositions record legitimate outcomes such as a phone resolution; they are not a ranking of individual staff.</p></div></div>; }
function QualityView({ rows, loading }: { rows: Unmatched[]; loading: boolean }) { return <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Database className="h-4 w-4 text-teal-700" />Unmatched senders</CardTitle><p className="text-sm font-normal text-slate-500">External senders that could not be connected to a known client contact. Review these to improve data quality.</p></CardHeader><CardContent className="p-0">{loading ? <div className="space-y-3 p-5">{[1, 2, 3].map((i) => <div key={i} className="h-12 animate-pulse rounded bg-slate-100" />)}</div> : !rows.length ? <div className="p-12 text-center text-sm text-slate-500">No unmatched senders found.</div> : <div className="overflow-x-auto"><table className="min-w-[700px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Sender</th><th className="px-5 py-3">Messages</th><th className="px-5 py-3">Mailboxes</th><th className="px-5 py-3">Last message</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.email}><td className="px-5 py-3"><p className="font-medium text-slate-800">{row.displayName || "Unknown sender"}</p><p className="text-xs text-slate-500">{row.email}</p></td><td className="px-5 py-3">{row.messageCount}</td><td className="px-5 py-3 text-slate-600">{row.mailboxes?.join(", ") || "Not recorded"}</td><td className="px-5 py-3 text-slate-600">{dateTime(row.lastMessageAt)}</td></tr>)}</tbody></table></div>}</CardContent></Card>; }
function SettingsView({ data, form, setForm, onSave, saving, onAdd, onToggle }: { data?: { settings: Settings; mailboxes: Mailbox[] }; form: Settings; setForm: (s: Settings) => void; onSave: () => void; saving: boolean; onAdd: () => void; onToggle: (id: number, enabled: boolean) => void }) {
  const current = data?.settings || {};
  const triageMode = form.autoTriageMode ?? current.autoTriageMode ?? "disabled";
  const confidence = form.autoTriageConfidenceThreshold ?? current.autoTriageConfidenceThreshold ?? 0.98;
  return <div className="grid gap-5 xl:grid-cols-[1fr_1.15fr]">
    <Card className="border-slate-200 shadow-sm">
      <CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="h-4 w-4 text-teal-700" />Service rules</CardTitle><p className="text-sm font-normal text-slate-500">Configure automatic mailbox updates and which contacts are treated as genuine clients.</p></CardHeader>
      <CardContent className="space-y-4">
        <label className="flex items-center justify-between rounded-md border border-slate-200 p-3 text-sm"><span><span className="block font-medium text-slate-800">Automatic mailbox refresh</span><span className="text-xs text-slate-500">Refresh every 30 minutes, including when nobody has Email Analytics open</span></span><input type="checkbox" checked={form.automaticRefreshEnabled ?? current.automaticRefreshEnabled ?? true} onChange={(e) => setForm({ ...form, automaticRefreshEnabled: e.target.checked })} /></label>
        <div className="grid grid-cols-3 gap-3"><div><Label>Day starts</Label><Input type="time" value={minutesToTime(form.workdayStartMinutes ?? current.workdayStartMinutes ?? 570)} onChange={(e) => setForm({ ...form, workdayStartMinutes: timeToMinutes(e.target.value) })} /></div><div><Label>Mon–Thu ends</Label><Input type="time" value={minutesToTime(form.workdayEndMinutes ?? current.workdayEndMinutes ?? 1050)} onChange={(e) => setForm({ ...form, workdayEndMinutes: timeToMinutes(e.target.value) })} /></div><div><Label>Friday ends</Label><Input type="time" value={minutesToTime(form.fridayEndMinutes ?? current.fridayEndMinutes ?? 870)} onChange={(e) => setForm({ ...form, fridayEndMinutes: timeToMinutes(e.target.value) })} /></div></div>
        <p className="text-xs text-slate-500">Retained for future use. These office hours do not drive the current Email Response SLA.</p>
        <div><Label>Karbon client contact types</Label><Input value={(form.contactTypes ?? current.contactTypes ?? []).join(", ")} onChange={(e) => setForm({ ...form, contactTypes: e.target.value.split(",").map(v => v.trim()).filter(Boolean) })} placeholder="Client, Client - Individual Tax" /></div>
        <div><Label>Refresh interval (minutes)</Label><Input type="number" min={30} max={1440} value={Math.max(30, form.syncIntervalMinutes ?? current.syncIntervalMinutes ?? 30)} onChange={(e) => setForm({ ...form, syncIntervalMinutes: Number(e.target.value) })} /><p className="mt-1 text-xs text-slate-500">30 minutes is recommended for 12 mailboxes. Incremental refreshes normally process only recent changes.</p></div>
        <div className="rounded-md border border-indigo-200 bg-indigo-50/50 p-3"><Label htmlFor="auto-triage-mode">Auto-triage mode</Label><select id="auto-triage-mode" className="mt-1 h-9 w-full rounded-md border border-slate-300 bg-white px-2 text-sm" value={triageMode} onChange={(e) => setForm({ ...form, autoTriageMode: e.target.value as "disabled" | "shadow" })}><option value="disabled">Disabled</option><option value="shadow">Shadow validation only</option></select><div className="mt-3"><Label htmlFor="auto-triage-confidence">Proposed exclusion confidence</Label><Input id="auto-triage-confidence" className="mt-1" type="number" min={0.95} max={1} step={0.001} value={confidence} onChange={(e) => setForm({ ...form, autoTriageConfidenceThreshold: Number(e.target.value) })} /></div><p className="mt-2 text-xs text-indigo-900">Automatic exclusions cannot be selected here. They require a validated report, recorded management review, an explicit confirmation, verified Bedrock zero retention, and separate Microsoft content-access approval.</p></div>
        <Button onClick={onSave} disabled={saving}>{saving ? "Saving..." : "Save service rules"}</Button>
      </CardContent>
    </Card>
    <Card className="border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-start justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><Mail className="h-4 w-4 text-teal-700" />Monitored mailboxes</CardTitle><p className="text-sm font-normal text-slate-500">Only mailboxes listed here contribute to the queue.</p></div><Button size="sm" variant="outline" onClick={onAdd}>Add mailbox</Button></CardHeader><CardContent className="space-y-2">{!data?.mailboxes?.length ? <p className="py-6 text-sm text-slate-500">No mailboxes configured.</p> : data.mailboxes.map((mailbox) => <div key={mailbox.id} className="flex items-center justify-between rounded-md border border-slate-200 px-3 py-2.5"><div><p className="text-sm font-medium text-slate-800">{mailbox.displayName || mailbox.address}</p>{mailbox.displayName && <p className="text-xs text-slate-500">{mailbox.address}</p>}</div><button onClick={() => onToggle(mailbox.id, !mailbox.enabled)} className={`rounded-full px-2.5 py-1 text-xs font-medium ${mailbox.enabled ? "bg-teal-50 text-teal-700" : "bg-slate-100 text-slate-500"}`}>{mailbox.enabled ? "Enabled" : "Disabled"}</button></div>)}</CardContent></Card>
    <div className="xl:col-span-2 flex gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600"><Info className="mt-0.5 h-4 w-4 shrink-0 text-slate-500" /><p>The SLA is 24 elapsed hours in UK local time, with Saturdays and Sundays excluded. If a deadline falls on a weekend it rolls forward while preserving the remaining allowance. Weekend receipts begin their SLA clock at Monday 00:00. UK bank holidays remain a V1 limitation. The service currently uses message metadata only.</p></div>
  </div>;
}
function ErrorState({ retry }: { retry: () => void }) { return <div className="rounded-lg border border-rose-200 bg-rose-50 p-10 text-center"><AlertCircle className="mx-auto h-8 w-8 text-rose-600" /><h2 className="mt-3 font-semibold text-rose-900">Email analytics is unavailable</h2><p className="mt-1 text-sm text-rose-700">We could not load the queue. Your existing data has not been changed.</p><Button variant="outline" className="mt-4" onClick={retry}>Try again</Button></div>; }